language: node_js
node_js:
  - 7
  - 6.10.0
deploy:
  provider: npm
  email: joakim@kemeny.se
  api_key:
    secure: Oyau5gqaqfW8Ow/gvywODPI0FERPPnxb/trZs1R3ySEaPpMjdHx7C7WBdocCi2kAZtW0hZqRTRKHOdk1NCNkgnK0SlF9maTjSOlWuEtsJKfLzw7qMjSD9SODAejl2arUhfSE7NGX5W6ElEcvit9vpzuW2esJgGmJM7Y2YvSZtCGT7xnMwmm9Rx5781q24yi1a6/eWCjTu+3UAMavSokyD3nhq6OgA5mW6hLsJSJiXhKH+/1aItbfu8Ru85eqt6u00mVVP0NMPJjl7Aus9ROOJ4tG2S2ycbsxuOGI89ettCYO+jn3+sPYMAFTbfLmLvS+Rs3X6E/FjbxWbkkpCaQMDpaZKh1/XJxYQRdpBTABexLYwfBb0QEoYoZFy8N5OXjmT9YmpZgtEtGj2ChIm5650vHFazAq50FDuyCVvL+X8KyLaeWmfs+gaTs/lKxIDqUIJ7msN20HeUZs5YYjZgTxUekcFvJzrq1OPQyQFIF32Neid51BKi96EXH7Fhol8Ow8NDNQwSXLc+aTYmQSuLO6c7CqeK8+h7YM+d/R6CeVVbjZsh4bRFbzA5oy/gJ2dTNDpQ7WJ1vhfr7p/gSmcIPwrAYkVMIR3nG0eAexqD4WkQsH7bxP6qsaXJ1FW2mKgwhEoXGHieEhGERTTai+ac0hpY+KcBfUghWpWpcbxi8c+ZQ=
  on:
    tags: true
    repo: joakimkemeny/jke-neutrino-preset-react-mobx
    branch: master
    node: 6.10.0
